#include<math.h>

#define ALPHABET_SIZE 4
#define KMER_SIZE 10
#define NUMBER_OF_BITS_FOR_EACH_KMER 4
#define NUMBER_OF_REGIONS 3
#define CONTIG_SIZE 150
#define NUMBER_OF_READS_CONTIGS 10000
#define NUMBER_OF_QUERIES_CONTIGS 1000

int NUMBER_OF_BIT_VECTOR_BYTES = ((NUMBER_OF_BITS_FOR_EACH_KMER*pow(4, KMER_SIZE))/8);
